name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate xcode project
      run: swift package generate-xcodeproj --enable-code-coverage
    - name: Generate xcode test report
      run: xcodebuild -scheme fluentinterface-Package clean test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.codecovToken }}
        fail_ci_if_error: true
